### PR TITLE
Crud And Functionality

### PR DESCRIPTION
**Pull request by niicode**
In this project I was able to Achieve the following:
- Added a Function to be able to add and remove todos
- Added a function to update todo
- Saved Todos to local storage

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @niicode, This is @sja-thedude your code reviewer.

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Professional Readme
✔️ All linters passing

## Required 
- [ ] Kindly fix the error when selected an option and clicked on clear all completed , all options are deleted.

https://user-images.githubusercontent.com/70269507/183931588-20dc8c49-594f-46e4-b81c-473011a5fedd.mov

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by niicode** [comment]
hi @sja-thedude thanks for the feedback but that task is supposed to be done tomorrow, todays task focuses on only add remove and updating of the task I personally just added the clearAll functionality but I will finish that in the next milestone.

**Comment by sja-thedude** [comment]
> hi @sja-thedude thanks for the feedback but that task is supposed to be done tomorrow, todays task focuses on only add remove and updating of the task I personally just added the clearAll functionality but I will finish that in the next milestone.

Oh okay, Actually this was not mentioned in my guidelines. You can ask for another review and your project will be approved.

**Review by Nemwel-Boniface — APPROVED** [review]
## Hello @niicode               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 



## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
